#include "Misc/AutomationTest.h"
#include "WMCYNJoinTicket.h"

#if WITH_DEV_AUTOMATION_TESTS

namespace
{
// RFC 4231 test case 2: key "Jefe", message "what do ya want for nothing?".
const uint8 GRfc4231Case2Expected[32] = {
    0x5b, 0xdc, 0xc1, 0x46, 0xbf, 0x60, 0x75, 0x4e, 0x6a, 0x04, 0x24, 0x26, 0x08, 0x95, 0x75, 0xc7,
    0x5a, 0x00, 0x3f, 0x08, 0x9d, 0x27, 0x39, 0x83, 0x9d, 0xec, 0x58, 0xb9, 0x64, 0xec, 0x38, 0x43
};

// Generated by the backend's Node joinTicket implementation with this secret;
// proves cross-implementation HMAC/base64url/JSON parity. exp is year 2100.
const TCHAR* GFixtureSecret = TEXT("wmcyn-cross-impl-test-secret-0123456789abcdef");
const TCHAR* GFixtureTicket = TEXT(
    "v1.eyJ0aWQiOiJmaXh0dXJlLXRpY2tldC0wMDAxIiwidWlkIjoiZml4dHVyZS11aWQiLCJ3b3JsZElkIjoid21jeW4tb25s"
    "aW5lIiwibG9jYXRpb25JZCI6IndtY3luLWNyaWIiLCJydW50aW1lSWQiOiJmaXh0dXJlLXJ1bnRpbWUiLCJidWlsZElkIjoi"
    "Zmlyc3Qtc2lnbmFsLTAwMSIsInByb3RvY29sVmVyc2lvbiI6MSwibW9kZSI6IlF1ZXN0Iiwic2xvdCI6IlN0YW5kYWxvbmVW"
    "Ul9BIiwiY2FwYWJpbGl0aWVzIjpbXSwiaWF0IjoxNzUyNTg1NjAwLCJleHAiOjQxMDI0NDQ4MDB9."
    "IfLccEaxKnLa-kWLYXtohMkJJLt5mnCK45F4xrwN8Ps");
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
    FWMCYNJoinTicketHmacVectorTest,
    "WMCYN.FirstSignal.JoinTicket.HmacSha256Rfc4231",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::ProductFilter)
bool FWMCYNJoinTicketHmacVectorTest::RunTest(const FString& Parameters)
{
    const ANSICHAR* Key = "Jefe";
    const ANSICHAR* Message = "what do ya want for nothing?";

    uint8 Digest[32];
    WMCYNJoinTicket::HmacSha256(
        TArrayView<const uint8>(reinterpret_cast<const uint8*>(Key), 4),
        TArrayView<const uint8>(reinterpret_cast<const uint8*>(Message), FCStringAnsi::Strlen(Message)),
        Digest);

    TestTrue(TEXT("HMAC-SHA256 matches RFC 4231 test case 2"),
        FMemory::Memcmp(Digest, GRfc4231Case2Expected, 32) == 0);
    return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
    FWMCYNJoinTicketNodeParityTest,
    "WMCYN.FirstSignal.JoinTicket.VerifiesNodeIssuedTicket",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::ProductFilter)
bool FWMCYNJoinTicketNodeParityTest::RunTest(const FString& Parameters)
{
    FWMCYNJoinTicketPayload Payload;
    TestTrue(TEXT("Node-issued ticket verifies"),
        WMCYNJoinTicket::VerifyJoinTicket(GFixtureSecret, GFixtureTicket, Payload));
    TestEqual(TEXT("uid"), Payload.Uid, TEXT("fixture-uid"));
    TestEqual(TEXT("runtimeId"), Payload.RuntimeId, TEXT("fixture-runtime"));
    TestEqual(TEXT("buildId"), Payload.BuildId, TEXT("first-signal-001"));
    TestEqual(TEXT("protocolVersion"), Payload.ProtocolVersion, 1);
    TestEqual(TEXT("slot"), Payload.Slot, TEXT("StandaloneVR_A"));
    TestEqual(TEXT("mode"), Payload.Mode, TEXT("Quest"));

    TestFalse(TEXT("Wrong secret fails"),
        WMCYNJoinTicket::VerifyJoinTicket(TEXT("wrong-secret-wrong-secret-wrong-secret"), GFixtureTicket, Payload));

    FString Tampered = GFixtureTicket;
    Tampered[20] = Tampered[20] == TEXT('a') ? TEXT('b') : TEXT('a');
    TestFalse(TEXT("Tampered payload fails"),
        WMCYNJoinTicket::VerifyJoinTicket(GFixtureSecret, Tampered, Payload));

    TestFalse(TEXT("Malformed ticket fails"),
        WMCYNJoinTicket::VerifyJoinTicket(GFixtureSecret, TEXT("v1.only-two-parts"), Payload));
    return true;
}

#endif
